### ISSUE TITLE
BinRead::Args<'a> not implementing Clone

### ISSUE THREAD

**Issue by GreatGodOfFire** [jam1garner/binrw#181]
Hello, I just updated my code from `binrw` `0.10` to `0.11` but now I encounter an error.
This is a boiled down version of my code: 
```rust
use binrw::{BinRead, VecArgs, Endian};

pub struct Foo;

impl BinRead for Foo {
    type Args<'a> = ();

    fn read_options<R: std::io::Read + std::io::Seek>(
        reader: &mut R,
        endian: Endian,
        _: Self::Args<'_>,
    ) -> binrw::BinResult<Self> {
        let data: Vec<u8> = Vec::read_options(reader, endian, VecArgs { count: 1, inner: () })?;
        Ok(Foo)
    }
}
```
And this is the error I am facing:
```rust
error[E0599]: the function or associated item `read_options` exists for struct `Vec<_, _>`, but its trait bounds were not satisfied
   --> src/main.rs:13:34
    |
13  |         let data: Vec<u8> = Vec::read_options(reader, endian, VecArgs { count: 1, inner: () })?;
    |                                  ^^^^^^^^^^^^ function or associated item cannot be called on `Vec<_, _>` due to unsatisfied trait bounds
    |
   ::: /home/greatgodoffire/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:400:1
    |
400 | pub struct Vec<T, #[unstable(feature = "allocator_api", issue = "32838")] A: Allocator = Global> {
    | ------------------------------------------------------------------------------------------------ doesn't satisfy `Vec<_>: BinRead`
    |
    = note: the following trait bounds were not satisfied:
            `<_ as BinRead>::Args<'a>: Clone`
            which is required by `Vec<_>: BinRead`
```
But the trait bound should be satisfied as `u8::Args<'a> = ()` and `()` implements `Clone`.
It worked with 0.10 so I would guess it has something to do with the lifetime added to `BinRead::Args`.
 Am I missing something here or is this a bug?
 Thanks for helping!

**Comment by kitlith** [comment]
Looks like you can fix this by replacing `let data: Vec<u8> = Vec::read_options(...)` with `let data = Vec::<u8>::read_options(...)`

There might be an equivalent fix by being more specific about the type of VecArgs, but I haven't found it yet.

This seems to work properly when using autogenerated impls using the derive macro.

**Comment by GreatGodOfFire** [comment]
Ah, thanks, it works now.
